In [1]:
#sys module
import sys
sys.version  # to get the version of python interpreter

'3.11.4 (main, Jul  5 2023, 14:15:25) [GCC 11.2.0]'

In [3]:
sys.path.insert(0,'c://Users/User/Downloads') #path is not permanently set..0->means we are checking frst in cwd,if its not present it will check in downloads folder
import usermodule
usermodule.food(1000,4)

Amount contributed by each 250.0


In [4]:
import os 
os.getcwd()

'/home/labuser'

In [5]:
#u can use sys module  at runtime for taking input for n  no.of variables
import sys
n=len(sys.argv)
for i in range(1,n):
    print(sys.argv[i],end=" ")
sum=0
for i in range(1,n):
    sum+=int(sys.argv[i])
print("ans",sum)

-f /home/labuser/.local/share/jupyter/runtime/kernel-4c1dcfe9-5bff-44d8-8ec9-b4a0795ae90e.json 

ValueError: invalid literal for int() with base 10: '-f'

In [ ]:
#check runtime arguments->args and kwargs in python

In [ ]:
#overriding in python ->when parent and child class has same function name ,then overriding happens

In [11]:
class Employee:
    def __init__(self,sal):
        self.salary=sal
    def show(self):
        print(self.salary)
class Incentives(Employee):
    def __init__(self,sal,inc):
        super().__init__(self,sal)
        self.incentive=inc
    def show(self):
        print(self.salary+self.incentive)
obj1=Employee(50000)
obj2=Incentives(1000)
obj2.show()
    

TypeError: Incentives.__init__() missing 1 required positional argument: 'inc'

In [ ]:
#https://www.geeksforgeeks.org/method-overriding-in-python/

In [ ]:
#getter and setter methods - used to acces private var

In [ ]:
class car:
    def __init__(self,a=40):
        self._speed=a
    def get_speed(self):
        return self._speed
    def set_speed(self,a):
        return self.__speed=a
        

In [ ]:
c1=car()
c1.getspeed()

In [ ]:
#data analysis

In [ ]:
#data visualizATION -> Pd,matplotlib,seaborn,plotly,geographical data

array ->homogeneous data,list->hetergenous data

In [12]:
import numpy as np

In [13]:
np_baseball=np.array([10,24,5,67])
np_baseball

array([10, 24,  5, 67])

In [16]:
ht=np.array([1.5,1.3,1.6])
wt=np.array([50,60,55])
BMI=wt/ht**2  #we can avaoid loops by using np_arrays
BMI

array([22.22222222, 35.50295858, 21.484375  ])

In [17]:
#addition
res=ht+wt
res

array([51.5, 61.3, 56.6])

In [20]:
ans=res>52
print(res)
print(res[ans])


[51.5 61.3 56.6]
[61.3 56.6]


In [22]:
#numpy demerits ->cannot contain elements with diff datatypes
a=np.array([10,20,30.0]) #bcoz of one float element others are changed to float
a

array([10., 20., 30.])

In [24]:
np_2d=np.array([[1,2,3],[4,5,6]])
print(np_2d[:,0:1])

[[1]
 [4]]


In [28]:
print(np_2d[1:,1:2])
np_2d.shape

[[5]]


(2, 3)

In [27]:
type(np_2d)

numpy.ndarray

In [29]:
np.dot(ht,wt)

241.0

In [30]:
np.ones([5,2],dtype=int) #creates numpy array with ones

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [31]:
np.zeros([3,3],dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [35]:
np.zeros([5,],dtype=int)

array([0, 0, 0, 0, 0])

In [41]:
np.zeros([1,1],dtype=int)

array([[0]])

In [43]:
np.arange(20).reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [45]:
#PANDAS
import pandas as pd

In [46]:
arr=np.array([10,20,40])
pd.Series(arr)

0    10
1    20
2    40
dtype: int64

In [48]:
#if you want to use custom labels
labels=['a','','c']
ser=pd.Series(arr,index=labels)
ser

a    10
     20
c    40
dtype: int64

In [49]:
ser['']

20

In [52]:
#Addition of series ->NaN as output is index is not present in both series
s1=pd.Series([1,2,3,4],['USA','GERMANY','USSR','JAPAN'])
s2=pd.Series([8,2,5,4],['USA','ASIA','JP','JAPAN']) 
s1+s2

ASIA       NaN
GERMANY    NaN
JAPAN      8.0
JP         NaN
USA        9.0
USSR       NaN
dtype: float64

In [54]:
import pandas as pd
import numpy as np
from numpy.random import randn
np.random.seed(101) #if seed is not used df will be diff everytime I run.To get a same df everytime use seed
df=pd.DataFrame(randn(5,4),['a','b','c','d','e'],['w','x','y','z'])
df

w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
c -2.018168  0.740122  0.528813 -0.589001
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [56]:

print(type(df))
print(type(df['w']))

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>


In [57]:
df['w']#extract one column from df

a    2.706850
b    0.651118
c   -2.018168
d    0.188695
e    0.190794
Name: w, dtype: float64

In [59]:
df[['w','x']]

w         x
a  2.706850  0.628133
b  0.651118 -0.319318
c -2.018168  0.740122
d  0.188695 -0.758872
e  0.190794  1.978757

In [60]:
df['new']=df['w']+df['x']
df

w         x         y         z       new
a  2.706850  0.628133  0.907969  0.503826  3.334983
b  0.651118 -0.319318 -0.848077  0.605965  0.331800
c -2.018168  0.740122  0.528813 -0.589001 -1.278046
d  0.188695 -0.758872 -0.933237  0.955057 -0.570177
e  0.190794  1.978757  2.605967  0.683509  2.169552

In [62]:
df=df.drop('new',axis=1)   #either assign drop output to df or else use inplace=True
df

w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
c -2.018168  0.740122  0.528813 -0.589001
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [63]:
df.loc['c']

w   -2.018168
x    0.740122
y    0.528813
z   -0.589001
Name: c, dtype: float64

In [ ]:
#matplotlib

In [ ]:
import matplotlib as mtp


In [ ]:
mtp.use('TkAgg')
import matplotlib.pyplot as plt
plt.plot(range(10))
plt.show()

In [ ]:

% matplotlib inline  #to show graph in same notebook
import matplotlib.pyplot as plt
plt.plot(range(10))
plt.show()

In [ ]:
import numpy as np
x=np.arange(0,10,0.1)
a=np.sin(x)
b=np.cos(x)
plt.plot(x,a,'r')  #r-red clr
plt.plot(x,b,'b')#b-blue clr
plt.show()

In [ ]:
#adding labels,title
x=np.linspace(0,5,11)
print(x)
y=x**2
plt.plot(x,y.'r-')
plt.xlabel('Emp_Exp')
plt.ylabel('Salaries')
plt.title('Financial Growth')
plt.show()
